FROM python:3.12.2-slim AS builder

WORKDIR /app

COPY . .

RUN pip install --upgrade pip
RUN pip install pipenv

COPY ./music-service/Pipfile .
COPY ./music-service/Pipfile.lock .

RUN pipenv install

FROM python:3.12.2-slim

WORKDIR /app/src
COPY --from=builder ./music-service/app/src .

CMD ["pipenv", "run", "server"]