FROM python:3.12.2-slim AS builder

WORKDIR /app

RUN pip install --upgrade pip
RUN pip install pipenv

COPY ./music-service/src ./src
COPY ./music-service/Pipfile ./Pipfile
COPY ./music-service/Pipfile.lock ./Pipfile.lock

RUN pipenv install
RUN pipenv requirements > requirements.txt

RUN pip install --no-cache-dir --upgrade -r requirements.txt
RUN pip install uvicorn

WORKDIR /app/src
RUN mkdir -p audio/saved

CMD ["uvicorn", "main:app", "--host=0.0.0.0" , "--reload" , "--port", "8000"]